import { Product, SkinType, MakeupStyle, FaceShape, ProductCategory } from "./types";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "p001",
    name: "无瑕持妆粉底液 SPF30",
    brand: "Lumina Beauty",
    category: "粉底",
    colors: ["象牙白", "自然色", "小麦色"],
    skinTypes: ["干性", "混合性", "中性"],
    styles: ["日常", "韩系"],
    faceShapeSupports: ["圆脸", "鹅蛋脸", "心形脸"],
    price: 299,
    image: "https://example.com/p001.jpg",
    purchaseUrl: "https://example.com/p001"
  },
  {
    id: "p002",
    name: "丝绒哑光口红 #18",
    brand: "VelvetGlow",
    category: "口红",
    colors: ["豆沙红", "正红", "砖红"],
    skinTypes: ["油性", "混合性", "中性"],
    styles: ["浓妆", "欧美风", "日常"],
    faceShapeSupports: ["所有脸型"],
    price: 189,
    image: "https://example.com/p002.jpg",
    purchaseUrl: "https://example.com/p002"
  },
  {
    id: "p003",
    name: "大地色系眼影盘",
    brand: "EyeMasters",
    category: "眼影",
    colors: ["棕褐色", "深咖", "米色", "香槟金"],
    skinTypes: ["所有肤质"],
    styles: ["日常", "欧美风", "复古"],
    faceShapeSupports: ["方脸", "长脸", "鹅蛋脸"],
    price: 249,
    image: "https://example.com/p003.jpg",
    purchaseUrl: "https://example.com/p003"
  },
  {
    id: "p004",
    name: "水润保湿遮瑕膏",
    brand: "CoverPerfect",
    category: "遮瑕",
    colors: ["肤色", "象牙白", "自然色"],
    skinTypes: ["干性", "敏感性"],
    styles: ["日常", "日系"],
    faceShapeSupports: ["圆脸", "心形脸", "鹅蛋脸"],
    price: 169,
    image: "https://example.com/p004.jpg",
    purchaseUrl: "https://example.com/p004"
  },
  {
    id: "p005",
    name: "高光提亮修容饼",
    brand: "ShinePro",
    category: "高光",
    colors: ["香槟金", "珍珠白", "玫瑰金"],
    skinTypes: ["油性", "混合性"],
    styles: ["派对", "浓妆"],
    faceShapeSupports: ["长脸", "方脸", "鹅蛋脸"],
    price: 219,
    image: "https://example.com/p005.jpg",
    purchaseUrl: "https://example.com/p005"
  },
  {
    id: "p006",
    name: "粉嫩腮红 #05",
    brand: "CheekPop",
    category: "腮红",
    colors: ["浅粉", "珊瑚粉", "蜜桃色"],
    skinTypes: ["干性", "中性"],
    styles: ["日常", "日系", "韩系"],
    faceShapeSupports: ["圆脸", "心形脸", "鹅蛋脸"],
    price: 149,
    image: "https://example.com/p006.jpg",
    purchaseUrl: "https://example.com/p006"
  },
  {
    id: "p007",
    name: "防水眼线液笔 #黑色",
    brand: "LineMaster",
    category: "眼线",
    colors: ["黑色", "深棕色"],
    skinTypes: ["所有肤质"],
    styles: ["浓妆", "欧美风", "复古"],
    faceShapeSupports: ["所有脸型"],
    price: 129,
    image: "https://example.com/p007.jpg",
    purchaseUrl: "https://example.com/p007"
  },
  {
    id: "p008",
    name: "睫毛膏 纤长浓密型",
    brand: "LashVolume",
    category: "睫毛",
    colors: ["黑色"],
    skinTypes: ["油性", "混合性"],
    styles: ["日常", "浓妆", "派对"],
    faceShapeSupports: ["所有脸型"],
    price: 159,
    image: "https://example.com/p008.jpg",
    purchaseUrl: "https://example.com/p008"
  },
  {
    id: "p009",
    name: "柔焦定妆喷雾",
    brand: "SetForever",
    category: "定妆",
    colors: ["透明"],
    skinTypes: ["干性", "油性", "混合性"],
    styles: ["所有风格"],
    faceShapeSupports: ["所有脸型"],
    price: 199,
    image: "https://example.com/p009.jpg",
    purchaseUrl: "https://example.com/p009"
  },
  {
    id: "p010",
    name: "奢华彩妆套组",
    brand: "LuxuryKit",
    category: "套组",
    colors: ["多色组合"],
    skinTypes: ["所有肤质"],
    styles: ["所有风格"],
    faceShapeSupports: ["所有脸型"],
    price: 899,
    image: "https://example.com/p010.jpg",
    purchaseUrl: "https://example.com/p010"
  }
];
