import os
base = r'C:\Users\yao\Documents\Ai美妆\admin\beauty-admin\src'

# Write a helper script
script = '''
import os
base = r'C:\\Users\\yao\\Documents\\Ai美妆\\admin\\beauty-admin\\src'

users_page = (
    'import React, { useEffect, useState } from "react";\\n'
    'import { fetchUsers, updateUserStatus } from "@services/userService";\\n'
    'import type { User, UserFilter } from "@/types";\\n'
    'import usePermission from "@guard/usePermission";\\n'
    'import Drawer from "@components/ui/Drawer";\\n'
    'import ConfirmModal from "@components/ui/ConfirmModal";\\n'
    'import "@/styles/table.css";\\n'
    '\\n'
    'const UsersPage: React.FC = () => {\\n'
    '  const [users, setUsers] = useState<User[]>([]);\\n'
    '  const [total, setTotal] = useState(0);\\n'
    '  const [page, setPage] = useState(1);\\n'
    '  const [loading, setLoading] = useState(true);\\n'
    '  const [filter, setFilter] = useState<UserFilter>({});\\n'
    '  const [selectedUser, setSelectedUser] = useState<User | null>(null);\\n'
    '  const [confirmModal, setConfirmModal] = useState({ open: false, user: null, action: null });\\n'
    '  const { can } = usePermission();\\n'
    '\\n'
    '  const loadData = async () => {\\n'
    '    setLoading(true);\\n'
    '    try {\\n'
    '      const res = await fetchUsers({ ...filter, page, pageSize: 10 });\\n'
    '      setUsers(res.items);\\n'
    '      setTotal(res.total);\\n'
    '    } finally {\\n'
    '      setLoading(false);\\n'
    '    }\\n'
    '  };\\n'
    '\\n'
    '  useEffect(() => { loadData(); }, [page]);\\n'
    '\\n'
    '  const handleFilter = () => { setPage(1); loadData(); };\\n'
    '  const handleReset = () => { setFilter({}); setPage(1); loadData(); };\\n'
    '\\n'
    '  const handleStatusChange = (user: User) => {\\n'
    '    const next = user.status === "active" ? "inactive" : user.status === "inactive" ? "active" : "banned";\\n'
    '    const action = next === "banned" ? "ban" : "activate";\\n'
    '    setConfirmModal({ open: true, user, action });\\n'
    '  };\\n'
    '\\n'
    '  const confirmStatusChange = async () => {\\n'
    '    const { user, action } = confirmModal;\\n'
    '    if (!user || !action) return;\\n'
    '    const next = action === "ban" ? "banned" : "active";\\n'
    '    await updateUserStatus(user.id, next);\\n'
    '    setConfirmModal({ open: false, user: null, action: null });\\n'
    '    loadData();\\n'
    '  };\\n'
    '\\n'
    '  const statusLabel = (s) => s === "active" ? "活跃" : s === "inactive" ? "不活跃" : "已封禁";\\n'
    '\\n'
    '  return (\\n'
    '    <div className="users-page">\\n'
    '      <div className="page-header"><h2 className="page-title">用户管理</h2></div>\\n'
    '      <div className="filters-bar">\\n'
    '        <input className="filter-input" placeholder="搜索昵称..." value={filter.keyword || ""} onChange={(e) => setFilter((f) => ({ ...f, keyword: e.target.value }))} />\\n'
    '        <select className="filter-select" value={filter.status || ""} onChange={(e) => setFilter((f) => ({ ...f, status: e.target.value || undefined }))}>\\n'
    '          <option value="">全部状态</option>\\n'
    '          <option value="active">活跃</option>\\n'
    '          <option value="inactive">不活跃</option>\\n'
    '          <option value="banned">已封禁</option>\\n'
    '        </select>\\n'
    '        <button className="filter-btn primary" onClick={handleFilter}>搜索</button>\\n'
    '        <button className="filter-btn secondary" onClick={handleReset}>重置</button>\\n'
    '      </div>\\n'
    '      <div className="table-card">\\n'
    '        <table className="data-table">\\n'
    '          <thead><tr><th>昵称</th><th>分析次数</th><th>报告数</th><th>Beauty Pro</th><th>状态</th><th>最近活跃</th><th>操作</th></tr></thead>\\n'
    '          <tbody>\\n'
    '            {loading ? <tr className="loading-row"><td colSpan={7}>加载中...</td></tr> :\\n'
    '              users.map((u) => (\\n'
    '                <tr key={u.id}>\\n'
    '                  <td><strong>{u.nickname}</strong></td>\\n'
    '                  <td>{u.totalAnalyses}</td>\\n'
    '                  <td>{u.totalReports}</td>\\n'
    '                  <td>{u.beautyPro ? "OK" : "--"}</td>\\n'
    '                  <td><span className={status-badge }>{statusLabel(u.status)}</span></td>\\n'
    '                  <td>{new Date(u.lastActiveAt).toLocaleDateString("zh-CN")}</td>\\n'
    '                  <td>\\n'
    '                    <button className="action-btn" onClick={() => setSelectedUser(u)}>详情</button>\\n'
    '                    {can("users", "edit") && (\\n'
    '                      <button className="action-btn" onClick={() => handleStatusChange(u)}>\\n'
    '                        {u.status === "active" ? "停用" : u.status === "inactive" ? "启用" : "解封"}\\n'
    '                      </button>\\n'
    '                    )}\\n'
    '                  </td>\\n'
    '                </tr>\\n'
    '              ))\\n'
    '            }\\n'
    '            {!loading && users.length === 0 && <tr><td colSpan={7} className="table-empty">暂无数据</td></tr>}\\n'
    '          </tbody>\\n'
    '        </table>\\n'
    '        {total > 0 && (\\n'
    '          <div className="pagination">\\n'
    '            <span>共 {total} 条</span>\\n'
    '            <div className="pagination-btns">\\n'
    '              <button className="page-btn" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>上一页</button>\\n'
    '              <span>第 {page} 页</span>\\n'
    '              <button className="page-btn" disabled={page >= Math.ceil(total / 10)} onClick={() => setPage((p) => p + 1)}>下一页</button>\\n'
    '            </div>\\n'
    '          </div>\\n'
    '        )}\\n'
    '      </div>\\n'
    '      <Drawer open={!!selectedUser} title="用户详情" onClose={() => setSelectedUser(null)} width="520px">\\n'
    '        {selectedUser && (\\n'
    '          <div className="user-detail">\\n'
    '            <div className="ud-avatar-row">\\n'
    '              <div className="ud-avatar">{selectedUser.nickname.charAt(0)}</div>\\n'
    '              <div><div className="ud-name">{selectedUser.nickname}</div><div className="ud-id">ID: {selectedUser.id}</div></div>\\n'
    '              <span className={status-badge } style={{ marginLeft: "auto" }}>{statusLabel(selectedUser.status)}</span>\\n'
    '            </div>\\n'
    '            <div className="ud-section-title">基本信息</div>\\n'
    '            <div className="ud-meta">\\n'
    '              <div className="ud-meta-item"><span className="ud-meta-label">注册时间</span><span className="ud-meta-value">{new Date(selectedUser.createdAt).toLocaleDateString("zh-CN")}</span></div>\\n'
    '              <div className="ud-meta-item"><span className="ud-meta-label">最近活跃</span><span className="ud-meta-value">{new Date(selectedUser.lastActiveAt).toLocaleString("zh-CN")}</span></div>\\n'
    '              <div className="ud-meta-item"><span className="ud-meta-label">Beauty Pro</span><span className="ud-meta-value">{selectedUser.beautyPro ? "已开通" : "--"}</span></div>\\n'
    '            </div>\\n'
    '            <div className="ud-section-title">数据统计</div>\\n'
    '            <div className="ud-stats">\\n'
    '              <div className="ud-stat"><span className="ud-stat-val">{selectedUser.totalAnalyses}</span><span className="ud-stat-lab">分析次数</span></div>\\n'
    '              <div className="ud-stat"><span className="ud-stat-val">{selectedUser.totalReports}</span><span className="ud-stat-lab">报告数</span></div>\\n'
    '              <div className="ud-stat"><span className="ud-stat-val">{selectedUser.sessionCount}</span><span className="ud-stat-lab">会话数</span></div>\\n'
    '            </div>\\n'
    '          </div>\\n'
    '        )}\\n'
    '      </Drawer>\\n'
    '      <ConfirmModal open={confirmModal.open} title={confirmModal.action === "ban" ? "封禁用户" : "启用用户"} message={confirmModal.action === "ban" ? 确定要封禁用户「」吗？ : 确定要启用用户「」吗？} variant={confirmModal.action === "ban" ? "danger" : "default"} confirmText={confirmModal.action === "ban" ? "确认封禁" : "确认启用"} onConfirm={confirmStatusChange} onCancel={() => setConfirmModal({ open: false, user: null, action: null })} />\\n'
    '    </div>\\n'
    '  );\\n'
    '};\\n'
    '\\n'
    'export default UsersPage;\\n'
)

with open(base + '/pages/users/UsersPage.tsx', 'w', encoding='utf-8') as f:
    f.write(users_page)
print('UsersPage written')
'''

with open(r'C:\Users\yao\Documents\Ai美妆\write_users.py', 'w', encoding='utf-8') as f:
    f.write(script)
print('script written')
