name = "beauty-mini-api"
main = "functions/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]

[[d1_databases]]
binding = "D1_DB"
database_name = "beauty-db"
database_id = "6d132245-24fc-463d-afb5-7ddb4619ec18"

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "beauty-images"

[[kv_namespaces]]
binding = "USER_CACHE"
id = "3370d3a1db49404aa2615c706a5e15eb"