import os

path = r'C:\Users\yao\Documents\Ai美妆\beauty-mini-v1\src\services\permission-service.ts'
lines = []
lines.append('/**')
lines.append(' * Permission Service - Handles report access via beauty-api-pages backend.')
lines.append(' * Uses server API for balance checks (source of truth).')
lines.append(' */')
lines.append('import type { BeautyReport, ReportAccess, ReportLevel } from "@/types";')
lines.append('import { REPORT_LEVELS } from "@/types/report-level";')
lines.append('import { getStorage, setStorage } from "@/utils/storage";')
lines.append('import userService from "./user-service";')
lines.append('import { request } from "@/services/api";')
lines.append('import { fetchServerBalance } from "@/services/token";')
lines.append('')
lines.append('class ReportPermissionService {')
lines.append('  private readonly STORAGE_KEY = "report_access_records";')
lines.append('')
lines.append('  private getStoredAccess(): ReportAccess[] {')
lines.append('    return getStorage<ReportAccess[]>(this.STORAGE_KEY, []) ?? [];')
lines.append('  }')
lines.append('')
lines.append('  private setStoredAccess(records: ReportAccess[]): void {')
lines.append('    setStorage(this.STORAGE_KEY, records);')
lines.append('  }')
lines.append('')
lines.append('  private async getCurrentUserId(): Promise<string> {')
lines.append('    try {')
lines.append('      const user = await userService.getCurrentUser();')
lines.append('      return user.userId;')
lines.append('    } catch {')
lines.append('      return "user_" + Date.now();')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  async hasAccess(reportId: string, userId?: string, level: ReportLevel = "first-look"): Promise<boolean> {')
lines.append('    const user = userId || await this.getCurrentUserId();')
lines.append('    try {')
lines.append('      const response = await request<{ success: boolean; allowed: boolean; tokenRequired: number; balance: number }>(')
lines.append('        "/api/beauty/access?reportLevel=" + encodeURIComponent(level),')
lines.append('        "GET"')
lines.append('      );')
lines.append('      if (response.success && response.data) {')
lines.append('        return response.data.allowed;')
lines.append('      }')
lines.append('    } catch {')
lines.append('      console.warn("[PermissionService] Backend access check failed, using local fallback");')
lines.append('    }')
lines.append('    const accessRecords = this.getStoredAccess();')
lines.append('    return accessRecords.some(r => r.reportId === reportId && r.unlocked && r.userId === user);')
lines.append('  }')
lines.append('')
lines.append('  isReportUnlocked(reportId: string, userId?: string): boolean {')
lines.append('    const user = userId || "unknown";')
lines.append('    const records = this.getStoredAccess();')
lines.append('    return records.some(r => r.reportId === reportId && r.unlocked && r.userId === user);')
lines.append('  }')
lines.append('')
lines.append('  async getAvailableLevel(userId?: string): Promise<ReportLevel> {')
lines.append('    const user = userId || await this.getCurrentUserId();')
lines.append('    try {')
lines.append('      const balanceResult = await fetchServerBalance(user);')
lines.append('      if (balanceResult.success && balanceResult.balance !== undefined) {')
lines.append('        const balance = balanceResult.balance;')
lines.append('        if (balance >= 3) return "beauty-pro";')
lines.append('        if (balance >= 1) return "style-upgrade";')
lines.append('        return "first-look";')
lines.append('      }')
lines.append('    } catch {')
lines.append('      // fall through')
lines.append('    }')
lines.append('    const { getAvailableCredits } = require("@/services/token");')
lines.append('    const quotas = getAvailableCredits(user);')
lines.append('    if (quotas.tokenCount >= 3) return "beauty-pro";')
lines.append('    if (quotas.tokenCount >= 1 || quotas.freeCount > 0) return "style-upgrade";')
lines.append('    return "first-look";')
lines.append('  }')
lines.append('')
lines.append('  async unlockReport(reportId: string, level: ReportLevel, userId?: string): Promise<{ success: boolean; message: string }> {')
lines.append('    const user = userId || await this.getCurrentUserId();')
lines.append('    const config = REPORT_LEVELS[level];')
lines.append('    if (!config || !config.enabled) {')
lines.append('      return { success: false, message: "报告等级不存在或已停用" };')
lines.append('    }')
lines.append('    if (config.isFree) {')
lines.append('      const access: ReportAccess = {')
lines.append('        reportId, userId: user, level, unlocked: true,')
lines.append('        unlockType: "free", tokenCost: 0,')
lines.append('        createdAt: new Date().toISOString(),')
lines.append('        expireAt: new Date(Date.now() + config.expireDays * 24 * 60 * 60 * 1000).toISOString()')
lines.append('      };')
lines.append('      const records = this.getStoredAccess();')
lines.append('      records.push(access);')
lines.append('      this.setStoredAccess(records);')
lines.append('      return { success: true, message: level + " 等级已解锁" };')
lines.append('    }')
lines.append('    try {')
lines.append('      const accessRes = await request<{ success: boolean; allowed: boolean; tokenRequired: number; balance: number }>(')
lines.append('        "/api/beauty/access?reportLevel=beauty-pro", "GET"')
lines.append('      );')
lines.append('      if (accessRes.success && accessRes.data && accessRes.data.allowed) {')
lines.append('        const access: ReportAccess = {')
lines.append('          reportId, userId: user, level, unlocked: true,')
lines.append('          unlockType: "token", tokenCost: config.tokenCost,')
lines.append('          createdAt: new Date().toISOString(),')
lines.append('          expireAt: new Date(Date.now() + config.expireDays * 24 * 60 * 60 * 1000).toISOString()')
lines.append('        };')
lines.append('        const records = this.getStoredAccess();')
lines.append('        records.push(access);')
lines.append('        this.setStoredAccess(records);')
lines.append('        return { success: true, message: "beauty-pro 等级已解锁" };')
lines.append('      }')
lines.append('    } catch { /* fall through */ }')
lines.append('    return { success: false, message: "Token不足：需要" + config.tokenCost + "个Token，当前余额不足" };')
lines.append('  }')
lines.append('')
lines.append('  async getReportContent(report: BeautyReport, userId?: string): Promise<BeautyReport> {')
lines.append('    return report;')
lines.append('  }')
lines.append('')
lines.append('  getActiveReportLevels(userId?: string): ReportAccess[] {')
lines.append('    const user = userId || "unknown";')
lines.append('    const now = new Date();')
lines.append('    return this.getStoredAccess().filter(r => r.userId === user && r.unlocked && new Date(r.expireAt) > now);')
lines.append('  }')
lines.append('}')
lines.append('')
lines.append('const permissionService = new ReportPermissionService();')
lines.append('export default permissionService;')

with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('permission-service.ts written:', len(lines), 'lines')
